MAX_SEED_VALUE = 1000000
NONE_COLOR = (0, 0, 0)
DEFAULT_NORMALIZATION_RANGE = (0, 1)
DEFAULT_CONFIG_PATH = 'default_world_config.json'
DEFAULT_OUTPUT_PATH = '../examples/generated_maps/default_config.png'
DEFAULT_SEED = 0
GRID_PIXEL_FREQUENCY = 10
GRID_COLOR = (0, 0, 0)
